コードレビューの対応
R-Tsukada/football-myteam pull request #177
Opened 2022-06-13 09:00 UTC by R-Tsukada

## 対応した issue
#176 
## 対応内容・対応背景・妥協点
コードレビューで指摘された内容の修正
## やったこと
- Gemfileのコメントとgemのズレを修正する
- routesの設定をresourcesで統一する
- Apiを大文字に変更する

## テスト

- [x] `bin/lint`を実行した
- [x] `bundle exec rspec`を実行した

2022-06-14 15:35 UTC, komagata requested changes

2022-06-14 15:35 UTC, komagata commented on config/routes.rb
> +  resources :home
この1行で色々なrouteが生成されていますが、全部使っている感じですかね？
もし一部しか使ってないとしたらonlyなどで制限してみてください〜

2022-06-15 02:27 UTC, R-Tsukada commented on config/routes.rb
> +  resources :home
`home`はindexしか使っていません。
なので`only: %i(index)`を追加しました。

2022-06-15 08:28 UTC, komagata reviewed
確認させて頂きました。OKです〜🙆‍♂️

2022-07-18 10:35 UTC, komagata commented on app/models/select_team.rb
> +    Team.find(team_id)
```suggestion
    user.favorite.team
```

こうではダメですかね？
そしてこれでOKであればメソッドを作る必要はないかも？

2022-07-18 12:09 UTC, R-Tsukada commented on app/models/select_team.rb
> +    Team.find(team_id)
`user.favorite.team`で大丈夫だったのでメソッドにするのをやめました!

2022-07-18 12:09 UTC, R-Tsukada commented on app/models/match_request.rb
> +  require 'net/http'
> requireは通常ファイルの一番上（fronzen_string_literalよりはした）に書くのが一般的なのでそうした方がいいかもです。
なぜかというと、これだとclassの中のスコープに読み込まれるように見えてしまいますが、loadと違ってrequireはそういった動きをせず、間違い安いからです。

そこまで考えてませんでした💦
修正しました！

2022-07-18 12:09 UTC, R-Tsukada commented on app/controllers/api/standings_controller.rb
> +    Year.season
メソッドにするのをやめて`Year.season`をそのまま使うようにしました！

2022-07-18 12:09 UTC, R-Tsukada commented on app/controllers/api/competitors_controller.rb
> +    @competitor_teams = Team.find(params.require(:id))
他のファイルも含めて修正しました！

2022-07-19 08:04 UTC, komagata commented
これらで追加されたmodelなどのテストの方も追加お願いします〜

2022-07-21 10:08 UTC, R-Tsukada commented on app/controllers/api/matches_controller.rb
> +    current_user.favorite.team
修正しました！

2022-07-21 10:09 UTC, R-Tsukada commented
テスト追加しました！

2022-07-21 17:13 UTC, komagata requested changes

2022-07-21 17:13 UTC, komagata commented on app/models/match_request.rb
> +require 'net/http'
これって両方ともrequireしないと動かないですかね？
試してないのでわからないですが、もしかしたらどちらか不要とかあるかもです〜

2022-07-21 17:13 UTC, komagata commented on spec/models/match_request_spec.rb
> +RSpec.describe MatchRequest, type: :model do
testのプラクティスでも書きましたが、modelについては、自分で実装したメソッドについては全てテストが必要になります〜

2022-08-03 02:26 UTC, R-Tsukada commented on app/models/match_request.rb
> +require 'net/http'
両方ともrequireせずに動きました🙏

2022-08-03 02:26 UTC, R-Tsukada commented on spec/models/match_request_spec.rb
> +RSpec.describe MatchRequest, type: :model do
テストを追加しました🙏

2022-08-03 21:29 UTC, R-Tsukada commented on spec/models/match_request_spec.rb
> +    match = MatchRequest
直接クラスを書くように修正しました🙏

2022-08-03 21:29 UTC, R-Tsukada commented on spec/models/match_request_spec.rb
> +  let(:array) { [favorite_url, competitor_url] }
`registered_team_url`という変数名に変更しました。

2022-08-03 21:29 UTC, R-Tsukada commented on app/models/year.rb
> +class Year < ApplicationRecord
DBに保存してません🙇‍♂️
継承しないように修正しました🙏

2022-08-03 21:29 UTC, R-Tsukada commented on app/models/standing_request.rb
> +  def self.save_standing(api)
こちらも`StandingReqest.create`に変更しました。

2022-08-03 21:29 UTC, R-Tsukada commented on app/models/match_request.rb
> +  def self.save_match(api)
`MatchRequest.create`に変更しました！

2022-08-04 08:40 UTC, komagata requested changes

2022-08-04 08:40 UTC, komagata commented on app/models/match_request.rb
> +class MatchRequest < ApplicationRecord
こちらはDBに保存していますか？もしDBを使っていなければ何も継承しないでいいと思います。
全てのモデルクラスについて確認してみてください〜

2022-08-04 08:40 UTC, komagata commented on spec/models/year_spec.rb
> +    current_year = Time.zone.now.year
現在時刻に依存するテストの場合は`travel_to`を使って時間を固定した方がいいと思います〜。

2022-08-04 08:40 UTC, komagata commented on app/controllers/api/standings_controller.rb
> +    Standing.all.delete_all
```suggestion
    Standing.delete_all
```

こんな感じで書けませんでしたっけ？

2022-08-04 08:40 UTC, komagata commented on spec/models/match_request_spec.rb
> +    manchester_united
ちょっと自信ないんですが、`FactoryBot.create`ではなく`FactoryBot.build`だけするのって意味ありましたっけ？

2022-08-04 08:40 UTC, komagata commented on spec/models/standing_request_spec.rb
> +  let(:registered_team_url) { [favorite_url, competitor_url] }
配列でしたら複数形にするのがrailsの流儀なので合わせた方がいいかもです〜

2022-08-04 14:46 UTC, R-Tsukada commented on app/models/match_request.rb
> +class MatchRequest < ApplicationRecord
ApplicationRecordの継承について理解が誤っていました🙇‍♂️
修正したので確認をお願いします🙏

2022-08-04 14:46 UTC, R-Tsukada commented on spec/models/year_spec.rb
> +    current_year = Time.zone.now.year
`travel_to`初めて知りました！
時間を固定して、テストを修正しました。

2022-08-04 14:46 UTC, R-Tsukada commented on app/controllers/api/standings_controller.rb
> +    Standing.all.delete_all
> こんな感じで書けませんでしたっけ？

かけました🙇‍♂️
`Standing.delete_all`に修正しました。

2022-08-04 14:46 UTC, R-Tsukada commented on spec/models/match_request_spec.rb
> +    manchester_united
すみません、そもそも必要ないコードでした🙇‍♂️

2022-08-04 14:46 UTC, R-Tsukada commented on spec/models/standing_request_spec.rb
> +  let(:registered_team_url) { [favorite_url, competitor_url] }
`registered_teams`という変数名に変更しました！

2022-08-05 07:10 UTC, komagata commented on spec/models/year_spec.rb
> +    travel_to Time.zone.local(2022, 7, 30)
travel_toは基本ブロックで使った方いいと思います。
元に戻すのを忘れずに済みますし、その時間に設定している範囲がどこまでなのか分かり易いからです。

2022-08-05 07:23 UTC, R-Tsukada commented on spec/models/year_spec.rb
> +    travel_to Time.zone.local(2022, 7, 30)
> travel_toは基本ブロックで使った方いいと思います。
元に戻すのを忘れずに済みますし、その時間に設定している範囲がどこまでなのか分かり易いからです。

たしかにそうですね。覚えておくようにします！
修正しました！

2022-08-05 07:59 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-08-05 12:19 UTC, merged